<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityManager;
use UserBundle\Entity\User;

/**
 * UserRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository
{
    private $userEntityClass = 'UserBundle\Entity\User';

    /**
     * @var EntityManager
     */
    private $entityManager;

    /**
     * UserRepository constructor.
     *
     * @param EntityManager $entityManager
     */
    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function find($id)
    {
        return $this->entityManager->find($this->userEntityClass, $id);
    }

    public function findAll()
    {
        $query = $this->entityManager
            ->createQueryBuilder()
            ->select('u')
            ->from($this->userEntityClass, 'u')
            ->orderBy('u.username', 'ASC')->getQuery();
        return $query->getResult();
    }
}
