parameters:
  user.repository.class: UserBundle\Repository\UserRepository
services:
    user_repository:
        class: UserBundle\Repository\UserRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    user_service:
        class: UserBundle\Service\User
        arguments:
            - '@user_repository'

    UserBundle\Controller\UserController:
      class: UserBundle\Controller\UserController
      arguments:
        - '@user_service'
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
