parameters:
  user.repository.class: AppBundle\Repository\UserRepository
services:
    user_repository:
        class: AppBundle\Repository\UserRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    user_service:
        class: AppBundle\Service\User
        arguments:
            - '@user_repository'

    AppBundle\Controller\UserController:
      class: AppBundle\Controller\UserController
      arguments:
        - '@user_service'
#    user.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
